### ISSUE TITLE
קבלת נתונים מגיבטהב

### ISSUE THREAD

**Issue by bennypowers** [RedHat-Israel/RedHat-Israel.github.io#12]
- [ ] לקבל נתונים על contributions מהעובדים בארץ דרך ממשק גיתהב
- [ ] לחשוף אותם ל11ty
- [ ] להריץ את הbuild בתדירות יומיומי כדי לעדכן אותם
- [ ] לעצב אותם כזה יפה

**Comment by bennypowers** [comment]
@TomerFi אם אני כותב קצת skeleton code בקשר לממשק גיטהב, תרצה ?לכתוב את השאר

**Comment by TomerFi** [comment]
אני אתחיל להתעסק עם השליפה.
