### ISSUE TITLE
Homepage content and design

### ISSUE THREAD

**Issue by bennypowers** [RedHat-Israel/RedHat-Israel.github.io#26]
- [x] stats on contributions
- [x] hero image from Israel site
- [x] add stats icons

**Comment by bennypowers** [comment]
@Liadredhat פה נרכז את השיחה על הדף הראשי

**Comment by ShiranHi** [comment]
I offer to do some changes:
1. Have a banner on this page, we can think about a title for it
2. Let's split visually the section of this page with backgrounds
3. Let's use cards and icons for the statistic part to make it more prominent

![image](https://user-images.githubusercontent.com/77277517/203309102-094565d1-65af-4484-97fc-7c2c8c65a8c7.png)

**Comment by ilan-pinto** [comment]
I will start with the icons.

**Comment by ilan-pinto** [comment]
@ShiranHi  where do we put the articles section? 
can we have 3 top articles links on the homepage?

**Comment by ShiranHi** [comment]
@ilan-pinto the Articles are the `פוסטים` section, no?
![image](https://user-images.githubusercontent.com/77277517/207025311-64d54a29-bc9a-4e50-bcd0-a1449fff4456.png)

Sure, we can add 3 top articles below the `פרוייקטים שאנחנו תורמים אליהם`section in the homepage, what do you think?
![image](https://user-images.githubusercontent.com/77277517/207026426-54bf53ee-1519-4ae7-aca8-e1a51e50a51c.png)

**Comment by bennypowers** [comment]
Looks great

**Comment by ilan-pinto** [comment]
@ShiranHi Amazing!!!
