### ISSUE TITLE
תרבות אירגונית

### ISSUE THREAD

**Issue by bennypowers** [RedHat-Israel/RedHat-Israel.github.io#3]
צריך כתבה על התרבות האירגונית הנפלאה של האתר ושל רדהט גלובלי

**Comment by mykaul** [comment]
מקומית (ובעברית) או קישור לאנגלית וכו'?

**Comment by bennypowers** [comment]
הכל פה יהיה מקומית ובעברית (לפחות, לא באנגלית)
