### ISSUE TITLE
add link to career site 

### ISSUE THREAD

**Issue by ilan-pinto** [RedHat-Israel/RedHat-Israel.github.io#57]
add to the site a link to Red Hat career job in Israel
this should be added to the sidebar menu 
 
https://careers-redhat.icims.com/jobs/search?ss=1&searchLocation=13269--Raanana&mobile=false&width=1140&height=500&bga=true&needsRedirect=false&jan1offset=120&jun1offset=180

**Comment by reihl** [comment]
It can be done as a html iframe with all the open positions:
![image](https://user-images.githubusercontent.com/23318984/211185602-da7a5b2e-4c40-487a-b20b-4dd919b70d9a.png)
